set(TOOLCHAIN_TRIPLE arm-nilrt-linux-gnueabi)
set(TOOLCHAIN_BASE_DIR ${CMAKE_CURRENT_LIST_DIR})
set(TOOLCHAIN_ROOTFS_DIR ${TOOLCHAIN_BASE_DIR}/${TOOLCHAIN_TRIPLE}/sysroot)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSROOT "${TOOLCHAIN_ROOTFS_DIR}")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-psabi")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-psabi")

set(CMAKE_C_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-g++)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-gfortran)

set(CMAKE_AR ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-ar)
set(CMAKE_AS ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-as)
set(CMAKE_NM ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-nm)
set(CMAKE_LINKER ${TOOLCHAIN_BASE_DIR}/bin/arm-frc2024-linux-gnueabi-ld)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

